server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://gilog.ccwyjdxrt15s.ap-northeast-2.rds.amazonaws.com:3306/gilog?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: dudthfalstjr12!
#    url: jdbc:mysql://localhost:3306/gilog?serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: dhsdk1977!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret-key: "SECRET_KEY123456789012345678901234567890"
