server:
  port: 8080

file:
  dir: /Users/kimyeongsol/Desktop/image/
#  dir: /home/ec2-user/image/
kakao:
  redirect-url: http://localhost:8080/api/oauth2/code/kakao
#  redirect-url: http://ec2-3-39-195-205.ap-northeast-2.compute.amazonaws.com:8080/api/oauth2/code/kakao

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gilog?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: dhsdk1977!
#    url: jdbc:mysql://gilog.ccwyjdxrt15s.ap-northeast-2.rds.amazonaws.com:3306/gilog?serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: dudthfalstjr12!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret-key: "SECRET_KEY123456789012345678901234567890"
