server:
  port: 8080

file:
#  dir: /Users/kimyeongsol/Desktop/image/
  dir: /home/ec2-user/image/
kakao:
#  redirect-url: http://localhost:8080/api/oauth2/code/kakao
#  redirect-url: http://ec2-43-200-108-131.ap-northeast-2.compute.amazonaws.com:8080/api/oauth2/code/kakao
  redirect-url: http://ec2-43-200-33-232.ap-northeast-2.compute.amazonaws.com:8080/api/oauth2/code/kakao

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/gilog?serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: dhsdk1977!
#    url: jdbc:mysql://gilog.ccwyjdxrt15s.ap-northeast-2.rds.amazonaws.com:3306/gilog?serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: dudthfalstjr12!
    url: jdbc:mysql://gi-log-database1.cf3waz1zsd5h.ap-northeast-2.rds.amazonaws.com:3306/gilog?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: LEEGAYOUNG0923!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret-key: "SECRET_KEY123456789012345678901234567890"
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
