server:
  port: 8081

file:
  dir: /home/ec2-user/image/

spring:
  datasource:
    url: jdbc:mysql://gi-log-database1.cf3waz1zsd5h.ap-northeast-2.rds.amazonaws.com:3306/gilog?serverTimezone=UTC&characterEncoding=utf8
    username: [USERNAME]
    password: [PASSWORD]
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: ssoyeong
      password: gilog2022!