server:
  port: 8081

file:
#  dir: /Users/kimyeongsol/Desktop/image/
  dir: /home/ec2-user/image/

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/gilog?serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: dhsdk1977!
#    url: jdbc:mysql://gilog.ccwyjdxrt15s.ap-northeast-2.rds.amazonaws.com:3306/gilog?serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: dudthfalstjr12!
    url: jdbc:mysql://gi-log-database1.cf3waz1zsd5h.ap-northeast-2.rds.amazonaws.com:3306/gilog?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: LEEGAYOUNG0923!
    driver-class-name: com.mysql.cj.jdbc.Driver
